adminapp/urls.py
from django.conf.urls import url

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    #url(r'^users/create/$', adminapp.user_create, name='user_create'),
    url(r'^users/create/$', adminapp.ShopUserCreateView.as_view(), name='user_create'),
    #url(r'^users/read/$', adminapp.users, name='users'),
    url(r'^users/read/$', adminapp.ShopUserListView.as_view(), name='users'),
    #url(r'^users/update/(?P<pk>\d+)/$', adminapp.user_update, name='user_update'),
    url(r'^users/update/(?P<pk>\d+)/$', adminapp.ShopUserUpdateView.as_view(), name='user_update'),
    #url(r'^users/delete/(?P<pk>\d+)/$', adminapp.user_delete, name='user_delete'),
    url(r'^users/delete/(?P<pk>\d+)/$', adminapp.ShopUserDeleteView.as_view(), name='user_delete'),
    url(r'^categories/create/$', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    url(r'^categories/read/$', adminapp.ProductCategoryListView.as_view(), name='categories'),
    #url(r'^categories/read/$', adminapp.ProductCategoryListView.as_view(), name='admin_custom'),
    url(r'^categories/update/(?P<pk>\d+)/$', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    url(r'^categories/delete/(?P<pk>\d+)/$', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),
    url(r'^products/create/category/(?P<pk>\d+)/$', adminapp.ProductCreateView.as_view(), name='product_create'),
    url(r'^products/read/category/(?P<pk>\d+)/$', adminapp.ProductListView.as_view(), name='products'),
    url(r'^products/read/(?P<pk>\d+)/$', adminapp.ProductDetailView.as_view(), name='product_read'),
    url(r'^products/update/(?P<pk>\d+)/$', adminapp.ProductUpdateView.as_view(), name='product_update'),
    #url(r'^products/update/(?P<pk>\d+)/$', adminapp.ProductUpdateView.as_view(), name='admin_custom'),
    # url(r'^products/delete/(?P<pk>\d+)/$', adminapp.ProductDeleteView.as_view(), name='product_delete'),
    url(r'^products/delete/(?P<pk>\d+)/$', adminapp.product_delete, name='product_delete'),
]

authapp/urls.py
from django.conf.urls import url

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    url(r'^login/', authapp.login, name='login'),
    url(r'^logout/', authapp.logout, name='logout'),
    url(r'^register/', authapp.register, name='register'),
    url(r'^edit/', authapp.edit, name='edit'),
    url(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/', authapp.verify, name='verify')
]

basketapp/urls.py
from django.conf.urls import url

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    url(r'^$', basketapp.basket, name='view'),
    url(r'^add/(?P<pk>\d+)/$', basketapp.basket_add, name='add'),
    url('remove/(?P<pk>\d+)/$', basketapp.basket_remove, name='remove'),
    url(r'^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$', basketapp.basket_edit, name='edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
import mainapp.views as mainapp
import authapp.views as authapp

if settings.DEBUG:
    import debug_toolbar

urlpatterns = [
    url(r'^$', mainapp.main, name='index'),
    url(r'^auth/', include('authapp.urls', namespace='auth')),
    url(r'^products/', include('mainapp.urls', namespace='products')),
    url(r'^showroom/', mainapp.showroom, name='showroom'),
    url(r'^contacts/', mainapp.contact, name='contacts'),
    url(r'^basket/', include('basketapp.urls', namespace='basket')),
    url(r'^admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    url(r'^admin/', admin.site.urls),
    #url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^social/', include('social_django.urls', namespace='social')),
    url(r'^zakaz/', include('ordersapp.urls', namespace='zakaz')),

]

if settings.DEBUG:
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.conf.urls import url
import mainapp.views as mainapp
from django.urls import path

app_name = 'mainapp'


urlpatterns = [
    url('^$', mainapp.products, name='products'),
    url(r'^(?P<pk>\d+)/$', mainapp.product, name='product'),
    url(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/$', mainapp.products, name='page'),
    #path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    url(r'^category/(?P<pk>\d+)/$', mainapp.products, name='category'),
]

ordersapp/urls.py
from django.conf.urls import url
import ordersapp.views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
    url(r'^$', ordersapp.OrderList.as_view(), name='zakazes_list'),
    url(r'^order/create/$', ordersapp.OrderItemsCreate.as_view(), name='zakaz_create'),
    url(r'^order/read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='zakaz_read'),
    url(r'^order/update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='zakaz_update'),
    url(r'^order/delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='zakaz_delete'),

    url(r'^order/forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='zakaz_forming_complete'),

]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    class Meta:
        verbose_name='Категория'
        verbose_name_plural='Категории'

    name = models.CharField(verbose_name='имя_категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание_категории', blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

# Create your models here.

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import ProductCategory, Product
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader import render_to_string
from django.http import JsonResponse


def get_hot_product():
    return Product.objects.all().order_by('?').first()


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).\
                                    exclude(pk=hot_product.pk)[:2]
    return same_products


def main(request):
    products = Product.objects.all().order_by('?')[:6]
    return render(request, 'mainapp/index.html',
    context={'title': 'home',
             'products': products,
             'main_menu': [{'href': 'index', 'name': 'home'},
                            {'href': 'showroom', 'name': 'showroom'},
                            {'href': 'contacts', 'name': 'contact'}
                           ]})


def products(request, pk=None, page=1):

    title = 'catalog'
    #categories = ProductCategory.objects.all()
    #basket = request.user.basket.all()[0] if request.user.is_authenticated else []

    if pk:
        if pk == '0':
            #Добавил к products = Product.objects.all()
            #products = Product.objects.all().order_by('?')[:6]
            products = Product.objects.filter(is_active=True).order_by('price')

            category = {'name': 'все',
                        'pk': 0}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            #products = Product.objects.filter(category__pk=pk).order_by('?')[:6]
            products = Product.objects.filter(category__pk=pk, is_active=True).order_by('price')

        paginator = Paginator(products, 12)
        try:
            products_paginator = paginator.page(page)
            print(len(products_paginator))
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)
        context = {
            'title': title,
            #'cat_menu': categories,
            'category': category,
            'products': products_paginator,
            #'products': products,
        }

        return render(request, 'mainapp/catalog.html', context)

    hot_product = get_hot_product()

    same_products = get_same_products(hot_product)

    context = {
        'title': 'products',
        #'cat_menu': categories,
        'hot_product': hot_product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/hot_products.html', context)


def product(request, pk):

    title = 'product_detailes'
    #category = get_object_or_404(ProductCategory, pk=pk)
    context = {
        'title': title,
        #'cat_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        #'category': category,
    }
    if request.is_ajax():
        product = get_object_or_404(Product, pk=pk)
        return JsonResponse({'result': product.price})

    return render(request, 'mainapp/product_detailes.html', context)


def contact(request):
    return render(request, 'mainapp/contacts.html',
    context={'title': 'contacts'})


def showroom(request):
    return render(request, 'mainapp/showroom.html',
    context={'title': 'showroom'})

# Create your views here.

mainapp/templates/mainapp/includes/inc_menu.html
{% load static %}
{% load custom_tags %}
<ul class="menu">
    <li>
        <a href="{% url 'basket:view' %}" class="menu-link">
            <span>
                {{ request.user|basket_total_cost }} руб.
           {# {% if basket %} #}
                 {# {{ basket.total_cost|floatformat:0 }} руб #}
                 {# ({{ basket.total_quantity }} шт) #}
           {#{% endif %} #}
            </span>
            <span>
                {{ request.user|basket_total_quantity }} шт.
            </span>
        </a>
    </li>

    {% if request.user.is_superuser %}
        <li>
            <a href="{% url 'admin_custom:categories' %}" class="menu-link">админка</a>
    {% endif %}
         </li>
    <li>
        <a href="{% url 'index' %}" class="{% if request.resolver_match.url_name == 'index' %}
        menu-link-active menu-link
         {% else %}
          menu-link
         {% endif %}
        ">домой</a>
    </li>
    <li>
        <a href="{% url 'products:products' %}" class="{% if request.resolver_match.namespace == 'products' %}
         menu-link-active menu-link
          {% else %}
          menu-link
          {% endif %}
    ">продукты</a>
    </li>

{#    <li><a href="#" class="menu-link">HISTORY </a></li>#}
{#    <li><a href="#" class="menu-link">SHOWROOM</a></li>#}
    <li>
        <a href="{% url 'contacts' %}" class="{% if request.resolver_match.url_name == 'contacts' %}
        menu-link-active menu-link
         {% else %}
          menu-link
         {% endif %}">контакты
        </a>
    </li>
    {% if user.is_anonymous %}
        <li >
            <a href="{% url 'auth:login' %}" class="menu-link"> вход </a>
        </li>
    {% else %}
        <a href="{% url 'auth:logout' %}" class="menu-link">Выход</a>
    {% endif %}
    {% if user.is_authenticated %}
        <li class="menu-link user-link">{{ user.username|default:'Пользователь' }}
            <ul class="menu-in">
                <li>
                    <a href="{% url 'auth:edit' %}">
                        профиль
                    </a>
                </li>
                <li>
                    <a href="{% url 'zakaz:zakazes_list' %}">
                        заказы
                    </a>
                </li>
            </ul>
       </li>
    {% endif %}
    <li>
        <a href="{% url 'index' %}" class="menu-link"><img src="{% static 'img/search.svg' %}" alt="search"></a>
    </li>
</ul>

mainapp/templates/mainapp/includes/inc_menu_cat.html
<ul class="sets-menu">
<li>
    <a href="{% url 'products:category' 0 %}"
       class="{% if request.resolver_match.kwargs.pk == '0' %}
                sets-menu-link-active sets-menu-link
                {% else %}
                    sets-menu-link
              {% endif %}">
      все
    </a>
</li>
    {%  for category in cat_menu %}
           <li>
                <a href="{% url 'products:category' category.pk %}"
         class="{% if request.resolver_match.kwargs.pk|add:'0' == category.pk %}
                  sets-menu-link-active sets-menu-link
                  {% else %}
                    sets-menu-link
                   {% endif %}">
                {{ category.name }}
                </a>
           </li>
               {% endfor %}
</ul>

mainapp/templates/mainapp/includes/inc_menu_cat_prodetails.html
<ul class="sets-menu-details">
<li>
    <a href="{% url 'products:category' 0 %}"
       class="{% if request.resolver_match.kwargs.pk == '0' %}
                sets-menu-link-active sets-menu-link
                {% else %}
                    sets-menu-link
              {% endif %}">
      все
    </a>
</li>
    {%  for category in cat_menu %}
           <li>
                <a href="{% url 'products:category' category.pk %}" class="sets-menu-link">
                {{ category.name }}
                </a>
           </li>
               {% endfor %}
</ul>