authapp/urls.py
from django.conf.urls import url

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    url(r'^login/', authapp.login, name='login'),
    url(r'^logout/', authapp.logout, name='logout'),
    url(r'^register/', authapp.register, name='register'),
    url(r'^edit/', authapp.edit, name='edit'),
    url(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/', authapp.verify, name='verify')
]

basketapp/urls.py
from django.conf.urls import url

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    url(r'^$', basketapp.basket, name='view'),
    url(r'^add/(?P<pk>\d+)/$', basketapp.basket_add, name='add'),
    url('remove/(?P<pk>\d+)/$', basketapp.basket_remove, name='remove'),
    url(r'^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$', basketapp.basket_edit, name='edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
import mainapp.views as mainapp
import authapp.views as authapp

if settings.DEBUG:
    import debug_toolbar

urlpatterns = [
    url(r'^$', mainapp.main, name='index'),
    url(r'^auth/', include('authapp.urls', namespace='auth')),
    url(r'^products/', include('mainapp.urls', namespace='products')),
    url(r'^showroom/', mainapp.showroom, name='showroom'),
    url(r'^contacts/', mainapp.contact, name='contacts'),
    url(r'^basket/', include('basketapp.urls', namespace='basket')),
    url(r'^admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    url(r'^admin/', admin.site.urls),
    #url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^social/', include('social_django.urls', namespace='social')),
    url(r'^zakaz/', include('ordersapp.urls', namespace='zakaz')),

]

if settings.DEBUG:
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.conf.urls import url
import mainapp.views as mainapp
from django.urls import path

app_name = 'mainapp'


urlpatterns = [
    url('^$', mainapp.products, name='products'),
    url(r'^(?P<pk>\d+)/$', mainapp.product, name='product'),
    url(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/$', mainapp.products, name='page'),
    #path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    url(r'^category/(?P<pk>\d+)/$', mainapp.products, name='category'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    class Meta:
        verbose_name='Категория'
        verbose_name_plural='Категории'

    name = models.CharField(verbose_name='имя_категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание_категории', blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

# Create your models here.

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import ProductCategory, Product
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader import render_to_string
from django.http import JsonResponse


def get_hot_product():
    return Product.objects.all().order_by('?').first()


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).\
                                    exclude(pk=hot_product.pk)[:2]
    return same_products


def main(request):
    products = Product.objects.all().order_by('?')[:6]
    return render(request, 'mainapp/index.html',
    context={'title': 'home',
             'products': products,
             'main_menu': [{'href': 'index', 'name': 'home'},
                            {'href': 'showroom', 'name': 'showroom'},
                            {'href': 'contacts', 'name': 'contact'}
                           ]})


def products(request, pk=None, page=1):

    title = 'catalog'
    #categories = ProductCategory.objects.all()
    #basket = request.user.basket.all()[0] if request.user.is_authenticated else []

    if pk:
        if pk == '0':
            #Добавил к products = Product.objects.all()
            #products = Product.objects.all().order_by('?')[:6]
            products = Product.objects.filter(is_active=True).order_by('price')

            category = {'name': 'все',
                        'pk': 0}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            #products = Product.objects.filter(category__pk=pk).order_by('?')[:6]
            products = Product.objects.filter(category__pk=pk, is_active=True).order_by('price')

        paginator = Paginator(products, 12)
        try:
            products_paginator = paginator.page(page)
            print(len(products_paginator))
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)
        context = {
            'title': title,
            #'cat_menu': categories,
            'category': category,
            'products': products_paginator,
            #'products': products,
        }

        return render(request, 'mainapp/catalog.html', context)

    hot_product = get_hot_product()

    same_products = get_same_products(hot_product)

    context = {
        'title': 'products',
        #'cat_menu': categories,
        'hot_product': hot_product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/hot_products.html', context)


def product(request, pk):

    title = 'product_detailes'
    #category = get_object_or_404(ProductCategory, pk=pk)
    context = {
        'title': title,
        #'cat_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        #'category': category,
    }
    if request.is_ajax():
        product = get_object_or_404(Product, pk=pk)
        return JsonResponse({'result': product.price})

    return render(request, 'mainapp/product_detailes.html', context)


def contact(request):
    return render(request, 'mainapp/contacts.html',
    context={'title': 'contacts'})


def showroom(request):
    return render(request, 'mainapp/showroom.html',
    context={'title': 'showroom'})

# Create your views here.

mainapp/templates/mainapp/base.html
 <!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
<title>
    {% block title %}
        {{ title|title }}
        {% endblock %}
</title>

    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>

<body class="body">
   <div class="wrapper">
    <div class="top">
        <div class="container">
         
          {% block menu %}   
          {% endblock %}
          
          {% block content %}  
          {% endblock %}         
        </div>
    </div>
    
    <div class="footer">
        <div class="container">
            <div class="footer-back">
                <div class="contact-block">
                    <div class="contact-headers">
                        <h3 class="contact-us">contact us</h3>
                        <h3 class="useful-inf">useful information</h3>
                        <h3 class="stay-touch">Let’s Stay in Touch!</h3>
                    </div>
                    <div class="contact-info">
                        <div class="address-block">
                            <a href="#" class="useful-link">
                                <p class="address-block-p1">132A Bridge Road Richmond VIC Australia.</p>
                            </a>
                            <a href="#" class="useful-link">
                                <p class="address-block-p2">Talk to us on 1300 132 info@interior.com
                                </p>
                            </a>

                        </div>
                        <div class="useful-text">

                            <div class="sales-text">
                                <a href="#" class="useful-link">
                                    <h3 class="h3-sales-text">Sales terms</h3>
                                </a>
                                <a href="#" class="useful-link">
                                    <h3 class="h3-sales-text">Customer care</h3>
                                </a>
                                <a href="#" class="useful-link">
                                    <h3 class="h3-sales-text">Delivery</h3>
                                </a>
                            </div>
                            <div class="sales-text1">
                                <a href="#" class="useful-link">
                                    <h3 class="h3-sales-text">Architect accounts</h3>
                                </a>
                                <a href="#" class="useful-link">
                                    <h3 class="h3-sales-text">Careers</h3>
                                </a>
                                <a href="#" class="useful-link">
                                    <h3 class="h3-sales-text">Exchanges & returns</h3>
                                </a>
                            </div>
                        </div>
                        <div class="email-block">
                            <p class="stay-touch-text">Suscribe to know about our latest news, products and special offers just for suscribers.</p>
                            <div class="email-field">
                                <input type="email" placeholder="your email address" name="login">
                                <input type="image" src="{% static 'img/send.png' %}" alt="OK" class="send">

                            </div>
                        </div>

                    </div>
                    <div class="bottom-part">
                        <h3 class="copyright-h3">&#169; Copyright - INTERIOR 2016. All Rights Reserved.</h3>
                        <div class="social-links">
                            <a href="#"><i class="fab fa-facebook-f"></i></a>
                            <a href="#"><i class="fab fa-twitter"></i></a>
                            <a href="#"><i class="fab fa-google-plus"></i></a>
                            <a href="#"><i class="fab fa-pinterest"></i></a>
                        </div>
                        <a href="#" class="useful-link">
                            <h3 class="terms-h3">Terms &#38; Conditions / Privacy policy &#38; Cookies</h3>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</body>

</html>

mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/base.html' %}
{% load static %}

    {% block menu %}
    <div class="top-catalog">
        <div class="header">
            <a class="logo" href="{% url 'index' %}"><img src="{% static 'img/logo.svg' %}" alt="logo"></a>
            {% include 'mainapp/includes/inc_menu.html' %}
        </div>
            <h2 class="top-h2">Наш продуктовый ряд</h2>

    </div>
    {% endblock %}

    {% block content %}
    <div class="product-sets">
    {% include 'mainapp/includes/inc_menu_cat.html' %}

        <div class="products">
            {% for product in products %}
                <a href="{% url 'products:product' product.pk %}" class="products-img">
                    <img width="370px" src="/media/{{ product.image }}" alt="product">
                </a>
            {% endfor %}
        </div>

        <div class="paginator">
              {% if products.has_previous %}
                <a style="text-decoration: none;" href="{% url 'products:page' category.pk products.previous_page_number %}">
                  <<
                </a>
              {% endif %}
              <span class="current">
                страница {{ products.number }} из
                {{ products.paginator.num_pages }}
              </span>
              {% if products.has_next %}
                    <a style="text-decoration: none;" href="{% url 'products:page' category.pk products.next_page_number %}">
                  >>
                </a>
              {% endif %}
        </div>


        <i class="fas fa-spinner"></i>
    </div>

        <div class="promo-product">
        <div class="promo-img1">
            <div class="promo-block">
                <h4 class="promo-exlusive">EXLUSIVE</h4>
                <h2 class="promo-name">Fishnet Chair</h2>
                <p class="promo-text">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt</p>
                <a href="#" class="button">order us <img src="{% static 'img/arrow.svg' %}" alt="arrow"></a>
            </div>

        </div>
        <div class="promo-img">
            <div class="promo-block">
                <h4 class="promo-exlusive">EXLUSIVE</h4>
                <h2 class="promo-name">Fishnet Chair</h2>
                <p class="promo-text">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt</p>
                <a href="#" class="button">order us <img src="{% static 'img/arrow.svg' %}" alt="arrow"></a>
            </div>
        </div>
    </div>

    {% endblock %}

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{%load static%}
            
            {% block menu %}
               <div class="top-catalog">
                <div class="header">
                    <a class="logo" href="{% url 'index' %}"><img src="{% static 'img/logo.svg' %}" alt="logo"></a>
                        {% include 'mainapp/includes/inc_menu.html' %}
                </div>

                    <h2 class="top-h2">Contact Us</h2>

            </div>
            {% endblock %}
            
            {% block content %}
                <div class="contact-data"></div>
            {% endblock %}
        

mainapp/templates/mainapp/hot_products.html
{% extends 'mainapp/base.html' %}
{% load static %}

            {% block menu %}
            <div class="top-catalog">
                <div class="header">
                    <a class="logo" href="{% url 'index' %}"><img src="{% static 'img/logo.svg' %}" alt="logo"></a>
                    {% include 'mainapp/includes/inc_menu.html' %}
                </div>
                    <h2 class="top-h2">Наш прдуктовый ряд</h2>

            </div>
            {% endblock %}

            {% block content %}
            <div class="product-sets">
            {% include 'mainapp/includes/inc_menu_cat.html' %}
            <br>
            <br>
            <br>
            <br>

                <div style="display: flex; flex-wrap: wrap;" class="category-products clearfix">
      <div style="margin: 15px" class="block">
          <div class="card" style="width: 22rem;">
              <img width="370px" src="/media/{{ hot_product.image }}" class="card-img-top" alt="product">
              <div class="card-body">
                  <h5 class="card-title">{{ hot_product.name }}</h5>
                  <br><br>
                  <div style="
                  color: red">Горячее предложение</div>
                  <br><br>
                  <a href="{% url 'products:product' hot_product.pk %}" class="button">order us
                      <img src="{% static 'img/arrow.svg' %}" alt="arrow"></a>
              </div>
          </div>
      </div>

    {% for product in same_products %}
        <div style="margin: 15px" class="block">
              <div class="card" style="width: 22rem;">
                  <img width="370px" src="/media/{{ product.image }}" class="card-img-top" alt="product">
                  <div class="card-body">
                      <h5 class="card-title">{{ product.name }}</h5>
                      <p class="card-text">{{ product.short_desc }}</p>
                      <br><br>
                  <a href="{% url 'products:product' product.pk %}" class="button">order us
                      <img src="{% static 'img/arrow.svg' %}" alt="arrow"></a>

                  </div>
              </div>
          </div>
    {% endfor %}
    </div>
            </div>

            {% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

            {% block menu %}
            <div class="slider padding-site">
                <div class="header">
                    <a class="logo" href="{% url 'index' %}"><img src="{% static 'img/logo.svg' %}" alt="logo"></a>
                    {% include 'mainapp/includes/inc_menu.html' %}
                </div>
                <div class="slider-text">
                    <h4 class="slider-h4">ТЕНДЕНЦИИ</h4>
                    <h2 class="slider-h2">Удобные стулья</h2>
                    <p class="slider-p">
                        Новый уровень комфорта. Отличные характеристики
                    </p>

                    <a href="#" class="button">заказать <img src="{% static 'img/arrow.svg' %}" alt="arrow"></a>
                </div>
                <div class="slider-pagination">
                    <a href="" class="circle"></a>
                    <a href="" class="circle circle-active"></a>
                    <a href="" class="circle"></a>
                </div>
            </div>
            {% endblock %}
            
            {% block content %}
            <div class="featured-product">
                <div class="tab-control">
                    <div class="featured-header">
                        <a href="#">
                            <h2 class="featured-h2">Featured</h2>
                        </a>
                        <a href="#">
                            <h4 class="new-h4">New</h4>
                        </a>
                    </div>
                    <a href="#" class="explore-link">
                        <div class="explore-arrow">
                            <h2 class="explore">explore all</h2>
                            <img src="{% static 'img/arrow.svg' %}" alt="strelka">
                        </div>
                    </a>
                </div>
                <div class="tab-content">
                    <div class="product-img">
                        <div class="product-images">
                            <a href="#" class="button-arrow"><img src="{% static 'img/icon-hover.svg' %}" alt="botton-arrow"></a>

                            <h4 class="product-h4">Fishnet Chair</h4>
                            <p class="product-text">Seat and back with upholstery made of cold cure foam</p>
                        </div>

                    </div>
                    <div class="product-img1">
                        <div class="product-images">
                            <a href="#" class="button-arrow"><img src="{% static 'img/icon-hover.svg' %}" alt="botton-arrow"></a>
                            <h4 class="product-h4">Fishnet Chair</h4>
                            <p class="product-text">Seat and back with upholstery made of cold cure foam</p>
                        </div>
                    </div>
                    <div class="product-img2">
                        <div class="product-images">
                            <a href="#" class="button-arrow"><img src="{% static 'img/icon-hover.svg' %}" alt="botton-arrow"></a>
                            <h4 class="product-h4">Fishnet Chair</h4>
                            <p class="product-text">Seat and back with upholstery made of cold cure foam</p>
                        </div>

                    </div>
                    <div class="product-img3">
                        <div class="product-images">
                            <a href="#" class="button-arrow"><img src="{% static 'img/icon-hover.svg' %}" alt="botton-arrow"></a>
                            <h4 class="product-h4">Fishnet Chair</h4>
                            <p class="product-text">Seat and back with upholstery made of cold cure foam</p>
                        </div>

                    </div>

                </div>
            </div>
            <div class="promo-product">
                <div class="promo-img1">
                    <div class="promo-block">
                        <h4 class="promo-exlusive">Эксклюзив</h4>
                        <h2 class="promo-name">Удобные стулья</h2>
                        <p class="promo-text">Новый уровень комфорта. Отличные характеристики</p>
                        <a href="#" class="button">заказать <img src="{% static 'img/arrow.svg' %}" alt="arrow"></a>
                    </div>

                </div>
                <div class="promo-img">
                    <div class="promo-block">
                        <h4 class="promo-exlusive">EXLUSIVE</h4>
                        <h2 class="promo-name">Fishnet Chair</h2>
                        <p class="promo-text">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt</p>
                        <a href="#" class="button">order us <img src="{% static 'img/arrow.svg' %}" alt="arrow"></a>
                    </div>
                </div>
            </div>
            <div class="trending-products">
                <div class="title">
                    <h4 class="title-h4">Trending Products</h4>
                    <a href="#" class="explore-link">
                        <div class="explore-arrow">
                            <h2 class="explore">explore all</h2>
                            <img src="{% static 'img/arrow.svg' %}" alt="strelka">
                        </div>
                    </a>

                </div>
{#                <div class="products">#}
{#                    <a href="#" class="products-img"><img src="/media/products_images/product-11.jpg" alt="image-trend"></a>#}
{#                    <a href="#" class="products-img"><img src="/media/products_images/product-21.jpg" alt="image-trand"></a>#}
{#                    <a href="#" class="products-img"><img src="/media/products_images/product-31.jpg" alt="image-trand"></a>#}
{#                    <a href="#" class="products-img"><img src="/media/products_images/product-41.jpg" alt="image-trand"></a>#}
{#                    <a href="#" class="products-img"><img src="/media/products_images/product-5.jpg" alt="image-trand"></a>#}
{#                    <a href="#" class="products-img"><img src="/media/products_images/product-6.jpg" alt="image-trand"></a>#}
{#                </div>#}
                <div class="products">
                    {% for product in products %}
                        <a href="{% url 'products:product' product.pk %}" class="products-img">
                            <img width="370px" src="/media/{{ product.image }}" alt="product">
                        </a>
                    {% endfor %}
                </div>
            </div>
            <div class="hot-deals">
                <div class="slider-text">
                    <h4 class="slider-h4-1">hot deal</h4>
                    <h2 class="slider-h2">Fishnet Chair</h2>
                    <p class="slider-p">
                        Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black
                    </p>
                    <a href="#" class="button">order us <img src="{% static 'img/arrow.svg' %}" alt="arrow"></a>
                </div>
                <div class="slider-pagination1">
                    <a href="" class="circle"></a>
                    <a href="" class="circle circle-active"></a>
                    <a href="" class="circle"></a>
                </div>
            </div>
            <div class="exclusive-products">
                <div class="block-content">
                    <div class="block-1">
                        <div class="promo-block2">
                            <h4 class="promo-exlusive">EXLUSIVE</h4>
                            <h2 class="promo-name">Fishnet Chair</h2>
                            <p class="promo-text2">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt</p>
                            <a href="#" class="button">order us <img src="{% static 'img/arrow.svg' %}" alt="arrow"></a>
                        </div>
                    </div>
                    <div class="block-2">
                        <a href="#" class="exclusive-product"><img src="/media/products_images/product-2-sm.jpg" alt="exclusive-image"></a>
                        <a href="#" class="exclusive-product"><img src="/media/products_images/product-3.jpg" alt="exclusive-image"></a>
                        <a href="#" class="exclusive-product"><img src="/media/products_images/product-4.jpg" alt="exclusive-image"></a>
                        <a href="#" class="exclusive-product"><img src="/media/products_images/product-5.jpg" alt="exclusive-image"></a>
                    </div>
                </div>
            </div>
            <div class="mobile-app">
                <div class="text-app">
                    <h3 class="mob-h3">mobile app</h3>
                    <h2 class="mob-h2">Find. Follow. Favorite.</h2>
                    <p class="mob-p">Save your favorites and share your style.</p>
                    <div class="web-store">
                        <a href="#"><img src="{% static 'img/app-store.jpg' %}" alt="apple"></a>
                        <a href="#"><img src="{% static 'img/app-store.jpg' %}" alt="google"></a>
                    </div>
                </div>

            </div>
{#{% if user.is_anonymous %}#}
{#        <h3>Привет!</h3><br>#}
{#        <div>#}
{#            Выполни<a href="{% url 'auth:login' %}"> вход </a> или#}
{#            <a href="{% url 'auth:register' %}">зарегистрируйся</a>#}
{#        </div>#}
{#    {% else %}#}
{#    <h2>Привет, <a href="{% url 'auth:edit' %}">{{ user.username|title }}</a>!</h2>#}
{#    {% endif %}#}
{#<div>{{ items.1 }}</div>#}
{#{% for item in items %}#}
{#    {% if item != 'item2' %}#}
{#        <p>{{ item }}</p>#}
{#    {% endif %}#}
{#{% endfor %}#}
{#                <br>#}
{#    {% if user.is_authenticated %}#}
{#        <a href="{% url 'auth:logout' %}">Выход</a>#}
{#    {% endif %}#}
            {% endblock %}
            

mainapp/templates/mainapp/product_detailes.html
{% extends 'mainapp/base.html' %}
{% load static %}

            {% block menu %}
            <div class="top-catalog-details">
                <div class="header">
                    <a class="logo" href="{% url 'index' %}"><img src="{% static 'img/logo.svg' %}" alt="logo"></a>
                    {% include 'mainapp/includes/inc_menu.html' %}
                </div>
                    <h2 class="top-h2-details">Подробнее о продукте</h2>

            </div>
            {% endblock %}

            {% block content %}
            <div class="sets-menu-box">

                    {% include 'mainapp/includes/inc_menu_cat_prodetails.html' %}
            </div>
            <div class="details-hot-deal">
                <img width="1140px" height="570px" src="/media/{{ product.image }}" alt="small-chair">
                <div class = "text-detail">
                    <h2 class = "promo_name_detail">Fishnet Chair</h2>
                    <h4 class="name_product">{{ product.name }}</h4>
                    <h4 class="name_category">{{ product.category }}</h4>
                    <p class="price">{{ product.price }} <span>руб</span></p>
                    <a href="{% url 'basket:add' product.pk %}" class="button_detail_product">order us
                        <img src="{% static 'img/arrow.svg' %}" alt="arrow"></a>
                </div>
            </div>
            {% endblock %}

mainapp/templates/mainapp/showroom.html
{% extends 'mainapp/base.html' %}
{% load static %}

            {% block menu %}
            <div class="slider padding-site">
                <div class="header">
                    <a class="logo" href="{% url 'index' %}"><img src="{% static 'img/logo.svg' %}" alt="logo"></a>
                     {% include 'mainapp/includes/inc_menu.html' %}
                </div>
            </div>
            {% endblock %}

            {% block content %}
                <div class="temp_div"></div>
            {% endblock %}